program TlsLib.Tests;
{

  Delphi DUnit Test Project
  -------------------------
  This project contains the DUnit test framework and the GUI/Console test
  runners. Add "CONSOLE_TESTRUNNER" to the conditional defines entry in the
  project options to use the console test runner. Otherwise the GUI test runner
  will be used by default.

}

{$WARN DUPLICATE_CTOR_DTOR OFF}

{$IFNDEF TESTINSIGHT}
  {$IFDEF CONSOLE_TESTRUNNER}
    {$APPTYPE CONSOLE}
  {$ENDIF}
{$ENDIF}

uses
  {$IFDEF TESTINSIGHT}
  TestInsight.DUnit,
  {$ELSE}
  Forms,
  TestFramework,
  GUITestRunner,
  TextTestRunner,
  {$ENDIF }
  TlpTlsAlert in '..\..\TlsLib\src\Common\TlpTlsAlert.pas',
  TlpTlsContentType in '..\..\TlsLib\src\Common\TlpTlsContentType.pas',
  TlpTlsVersion in '..\..\TlsLib\src\Common\TlpTlsVersion.pas',
  TlpTlsLibExceptions in '..\..\TlsLib\src\Common\TlpTlsLibExceptions.pas',
  TlpTlsError in '..\..\TlsLib\src\Common\TlpTlsError.pas',
  TlpISecretBuffer in '..\..\TlsLib\src\Interfaces\Security\TlpISecretBuffer.pas',
  TlpSecureMemory in '..\..\TlsLib\src\Security\TlpSecureMemory.pas',
  TlpSecretBuffer in '..\..\TlsLib\src\Security\TlpSecretBuffer.pas',
  TlpWireReader in '..\..\TlsLib\src\Codec\TlpWireReader.pas',
  TlpWireVectorMarker in '..\..\TlsLib\src\Codec\TlpWireVectorMarker.pas',
  TlpIWireWriter in '..\..\TlsLib\src\Interfaces\Codec\TlpIWireWriter.pas',
  TlpWireWriter in '..\..\TlsLib\src\Codec\TlpWireWriter.pas',
  TlpCryptoAlgorithms in '..\..\TlsLib\src\Crypto\TlpCryptoAlgorithms.pas',
  TlpICryptoProvider in '..\..\TlsLib\src\Interfaces\Crypto\TlpICryptoProvider.pas',
  TlpISigningKey in '..\..\TlsLib\src\Interfaces\Crypto\TlpISigningKey.pas',
  TlpDefaultCryptoProvider in '..\..\TlsLib\src\Crypto\TlpDefaultCryptoProvider.pas',
  TlpINamedGroup in '..\..\TlsLib\src\Interfaces\Crypto\TlpINamedGroup.pas',
  TlpNamedGroups in '..\..\TlsLib\src\Crypto\TlpNamedGroups.pas',
  TlpArrayUtilities in '..\..\TlsLib\src\Common\TlpArrayUtilities.pas',
  TlpDataEncoding in '..\..\TlsLib\src\Common\TlpDataEncoding.pas',
  TlpDateTimeUtilities in '..\..\TlsLib\src\Common\TlpDateTimeUtilities.pas',
  TlpIClock in '..\..\TlsLib\src\Interfaces\Common\TlpIClock.pas',
  TlpClock in '..\..\TlsLib\src\Common\TlpClock.pas',
  TlpSessionTicketStrategy in '..\..\TlsLib\src\Session\TlpSessionTicketStrategy.pas',
  TlpCodeKeyedRegistry in '..\..\TlsLib\src\Common\TlpCodeKeyedRegistry.pas',
  TlpBitOperations in '..\..\TlsLib\src\Common\TlpBitOperations.pas',
  TlpBinaryPrimitives in '..\..\TlsLib\src\Common\TlpBinaryPrimitives.pas',
  TlpEnumUtilities in '..\..\TlsLib\src\Common\TlpEnumUtilities.pas',
  TlpRecordHeader in '..\..\TlsLib\src\Record\TlpRecordHeader.pas',
  TlpIRecordProtection in '..\..\TlsLib\src\Interfaces\Record\TlpIRecordProtection.pas',
  TlpRecordProtection in '..\..\TlsLib\src\Record\TlpRecordProtection.pas',
  TlpRecordLayer in '..\..\TlsLib\src\Record\TlpRecordLayer.pas',
  TlpTlsAlertProtocol in '..\..\TlsLib\src\Common\TlpTlsAlertProtocol.pas',
  TlpAlertMapping in '..\..\TlsLib\src\Common\TlpAlertMapping.pas',
  TlpITlsEngine in '..\..\TlsLib\src\Interfaces\Engine\TlpITlsEngine.pas',
  TlpITlsEventSink in '..\..\TlsLib\src\Interfaces\Engine\TlpITlsEventSink.pas',
  TlpTlsEngineEvents in '..\..\TlsLib\src\Engine\TlpTlsEngineEvents.pas',
  TlpTlsEngine in '..\..\TlsLib\src\Engine\TlpTlsEngine.pas',
  TlpHkdfLabel in '..\..\TlsLib\src\KeySchedule\TlpHkdfLabel.pas',
  TlpIKeySchedule in '..\..\TlsLib\src\Interfaces\KeySchedule\TlpIKeySchedule.pas',
  TlpTrafficKeys in '..\..\TlsLib\src\KeySchedule\TlpTrafficKeys.pas',
  TlpTls13KeySchedule in '..\..\TlsLib\src\KeySchedule\TlpTls13KeySchedule.pas',
  TlpTls12KeySchedule in '..\..\TlsLib\src\KeySchedule\TlpTls12KeySchedule.pas',
  TlpRecordProtectionFactory in '..\..\TlsLib\src\Record\TlpRecordProtectionFactory.pas',
  TlpHandshakeMessage in '..\..\TlsLib\src\Handshake\TlpHandshakeMessage.pas',
  TlpITranscriptHash in '..\..\TlsLib\src\Interfaces\Handshake\TlpITranscriptHash.pas',
  TlpIHandshakeChannel in '..\..\TlsLib\src\Interfaces\Handshake\TlpIHandshakeChannel.pas',
  TlpTranscriptHash in '..\..\TlsLib\src\Handshake\TlpTranscriptHash.pas',
  TlpHandshakeMessages in '..\..\TlsLib\src\Handshake\TlpHandshakeMessages.pas',
  TlpHandshakeEffect in '..\..\TlsLib\src\Handshake\TlpHandshakeEffect.pas',
  TlpIHandshakeMachine in '..\..\TlsLib\src\Interfaces\Handshake\TlpIHandshakeMachine.pas',
  TlpHandshakeChannel in '..\..\TlsLib\src\Handshake\TlpHandshakeChannel.pas',
  TlpHandshakeDriver in '..\..\TlsLib\src\Handshake\TlpHandshakeDriver.pas',
  TlpTls13HandshakeBase in '..\..\TlsLib\src\Handshake\TlpTls13HandshakeBase.pas',
  TlpHandshakeMachineBase in '..\..\TlsLib\src\Handshake\TlpHandshakeMachineBase.pas',
  TlpTls12ServerStateMachine in '..\..\TlsLib\src\Handshake\TlpTls12ServerStateMachine.pas',
  TlpTls12ClientStateMachine in '..\..\TlsLib\src\Handshake\TlpTls12ClientStateMachine.pas',
  TlpVersionDispatchMachine in '..\..\TlsLib\src\Handshake\TlpVersionDispatchMachine.pas',
  TlpHelloRetryCookie in '..\..\TlsLib\src\Handshake\TlpHelloRetryCookie.pas',
  TlpCertificateCompression in '..\..\TlsLib\src\CertCompression\TlpCertificateCompression.pas',
  TlpCertificateLimits in '..\..\TlsLib\src\Trust\TlpCertificateLimits.pas',
  TlpTrustPolicy in '..\..\TlsLib\src\Trust\TlpTrustPolicy.pas',
  TlpITlsTransport in '..\..\TlsLib\src\Interfaces\Engine\TlpITlsTransport.pas',
  TlpTlsConnectionInfo in '..\..\TlsLib\src\Engine\TlpTlsConnectionInfo.pas',
  TlpTlsStreamPump in '..\..\TlsLib\src\Engine\TlpTlsStreamPump.pas',
  TlpTlsStream in '..\..\TlsLib\src\Engine\TlpTlsStream.pas',
  TlpIHttpFetcher in '..\..\TlsLib\src\Interfaces\Trust\TlpIHttpFetcher.pas',
  TlpLiveRevocation in '..\..\TlsLib\src\Trust\TlpLiveRevocation.pas',
  TlpICertificateCompression in '..\..\TlsLib\src\Interfaces\CertCompression\TlpICertificateCompression.pas',
  TlpICertificateCompressionCache in '..\..\TlsLib\src\Interfaces\CertCompression\TlpICertificateCompressionCache.pas',
  TlpZlibCertificateCompression in '..\..\TlsLib\src\CertCompression\TlpZlibCertificateCompression.pas',
  TlpInMemoryCertificateCompressionCache in '..\..\TlsLib\src\CertCompression\TlpInMemoryCertificateCompressionCache.pas',
  TlpTls13ClientStateMachine in '..\..\TlsLib\src\Handshake\TlpTls13ClientStateMachine.pas',
  TlpTls13ServerStateMachine in '..\..\TlsLib\src\Handshake\TlpTls13ServerStateMachine.pas',
  TlpHandshakeConductor in '..\..\TlsLib\src\Handshake\TlpHandshakeConductor.pas',
  TlpCertificateVerify in '..\..\TlsLib\src\Handshake\TlpCertificateVerify.pas',
  TlpICertificateTrust in '..\..\TlsLib\src\Interfaces\Trust\TlpICertificateTrust.pas',
  TlpEndpointIdentity in '..\..\TlsLib\src\Trust\TlpEndpointIdentity.pas',
  TlpCertificateVerifier in '..\..\TlsLib\src\Trust\TlpCertificateVerifier.pas',
  TlpTlsCredential in '..\..\TlsLib\src\Handshake\TlpTlsCredential.pas',
  TlpITlsCredentialResolver in '..\..\TlsLib\src\Interfaces\Handshake\TlpITlsCredentialResolver.pas',
  TlpCredentialResolvers in '..\..\TlsLib\src\Handshake\TlpCredentialResolvers.pas',
  TlpITlsConfig in '..\..\TlsLib\src\Interfaces\Engine\TlpITlsConfig.pas',
  TlpITlsConfigBuilder in '..\..\TlsLib\src\Interfaces\Engine\TlpITlsConfigBuilder.pas',
  TlpTlsConfigBuilder in '..\..\TlsLib\src\Engine\TlpTlsConfigBuilder.pas',
  TlpTlsPresets in '..\..\TlsLib\src\Engine\TlpTlsPresets.pas',
  TlpTlsLib in '..\..\TlsLib\src\Engine\TlpTlsLib.pas',
  TlpITlsConfigMemo in '..\..\TlsLib\src\Interfaces\Engine\TlpITlsConfigMemo.pas',
  TlpTlsConfigMemo in '..\..\TlsLib\src\Engine\TlpTlsConfigMemo.pas',
  TlpTlsSignatureBuilder in '..\..\TlsLib\src\Engine\TlpTlsSignatureBuilder.pas',
  TlpTlsEngineFactory in '..\..\TlsLib\src\Engine\TlpTlsEngineFactory.pas',
  TlpExtensionContext in '..\..\TlsLib\src\Extensions\TlpExtensionContext.pas',
  TlpITlsExtension in '..\..\TlsLib\src\Interfaces\Extensions\TlpITlsExtension.pas',
  TlpExtensionBlockCodec in '..\..\TlsLib\src\Extensions\TlpExtensionBlockCodec.pas',
  TlpCoreExtensions in '..\..\TlsLib\src\Extensions\TlpCoreExtensions.pas',
  TlpSessionExtensions in '..\..\TlsLib\src\Extensions\TlpSessionExtensions.pas',
  TlpGrease in '..\..\TlsLib\src\Extensions\TlpGrease.pas',
  TlpNegotiationTypes in '..\..\TlsLib\src\Negotiation\TlpNegotiationTypes.pas',
  TlpINegotiation in '..\..\TlsLib\src\Interfaces\Negotiation\TlpINegotiation.pas',
  TlpCipherSuiteRegistry in '..\..\TlsLib\src\Negotiation\TlpCipherSuiteRegistry.pas',
  TlpSignatureSchemeRegistry in '..\..\TlsLib\src\Negotiation\TlpSignatureSchemeRegistry.pas',
  TlpNegotiationPolicy in '..\..\TlsLib\src\Negotiation\TlpNegotiationPolicy.pas',
  TlpISession in '..\..\TlsLib\src\Interfaces\Session\TlpISession.pas',
  TlpSession in '..\..\TlsLib\src\Session\TlpSession.pas',
  TlpExternalPskImporter in '..\..\TlsLib\src\Session\TlpExternalPskImporter.pas',
  TlpInMemorySessionCache in '..\..\TlsLib\src\Session\TlpInMemorySessionCache.pas',
  TlpInMemorySessionStore in '..\..\TlsLib\src\Session\TlpInMemorySessionStore.pas',
  TlpSessionTicketKeys in '..\..\TlsLib\src\Session\TlpSessionTicketKeys.pas',
  TlpAntiReplay in '..\..\TlsLib\src\Session\TlpAntiReplay.pas',
  TlsLibTestResourceLoader in '..\src\TlsLibTestResourceLoader.pas',
  TlsLibTestBase in '..\src\TlsLibTestBase.pas',
  SecretTests in '..\src\SecretTests.pas',
  AlertTests in '..\src\AlertTests.pas',
  ExceptionTests in '..\src\ExceptionTests.pas',
  WireCodecTests in '..\src\WireCodecTests.pas',
  ProviderTests in '..\src\ProviderTests.pas',
  NamedGroupTests in '..\src\NamedGroupTests.pas',
  MockRandom in '..\src\MockRandom.pas',
  MockCryptoProvider in '..\src\MockCryptoProvider.pas',
  MockTests in '..\src\MockTests.pas',
  RecordHeaderTests in '..\src\RecordHeaderTests.pas',
  RecordProtectionTests in '..\src\RecordProtectionTests.pas',
  RecordLayerTests in '..\src\RecordLayerTests.pas',
  AlertProtocolTests in '..\src\AlertProtocolTests.pas',
  EngineSkeletonTests in '..\src\EngineSkeletonTests.pas',
  HkdfLabelTests in '..\src\HkdfLabelTests.pas',
  Tls13KeyScheduleTests in '..\src\Tls13KeyScheduleTests.pas',
  Tls12KeyScheduleTests in '..\src\Tls12KeyScheduleTests.pas',
  ScheduleInstallTests in '..\src\ScheduleInstallTests.pas',
  HandshakeMessageTests in '..\src\HandshakeMessageTests.pas',
  TranscriptHashTests in '..\src\TranscriptHashTests.pas',
  HandshakeMessagesTests in '..\src\HandshakeMessagesTests.pas',
  HandshakeDriverTests in '..\src\HandshakeDriverTests.pas',
  Tls13ClientReplayTests in '..\src\Tls13ClientReplayTests.pas',
  Tls13ServerReplayTests in '..\src\Tls13ServerReplayTests.pas',
  HelloRetryRequestTests in '..\src\HelloRetryRequestTests.pas',
  ExtensionNegotiationTests in '..\src\ExtensionNegotiationTests.pas',
  ResourceLimitTests in '..\src\ResourceLimitTests.pas',
  Tls13LoopbackTests in '..\src\Tls13LoopbackTests.pas',
  Tls12LoopbackTests in '..\src\Tls12LoopbackTests.pas',
  Tls12DualVersionTests in '..\src\Tls12DualVersionTests.pas',
  ClientAuthTests in '..\src\ClientAuthTests.pas',
  SessionStoreTests in '..\src\SessionStoreTests.pas',
  CertificateCompressionCacheTests in '..\src\CertificateCompressionCacheTests.pas',
  DataEncodingTests in '..\src\DataEncodingTests.pas',
  MockSessionStores in '..\src\MockSessionStores.pas',
  Tls13ResumptionTests in '..\src\Tls13ResumptionTests.pas',
  Tls12ResumptionTests in '..\src\Tls12ResumptionTests.pas',
  ConfigResumptionTests in '..\src\ConfigResumptionTests.pas',
  Tls13KeyUpdateTests in '..\src\Tls13KeyUpdateTests.pas',
  SignatureTests in '..\src\SignatureTests.pas',
  CredentialImportTests in '..\src\CredentialImportTests.pas',
  Pkcs12ImportTests in '..\src\Pkcs12ImportTests.pas',
  TlsStreamLoopbackTests in '..\src\TlsStreamLoopbackTests.pas',
  EndpointIdentityTests in '..\src\EndpointIdentityTests.pas',
  CertificateVerifierTests in '..\src\CertificateVerifierTests.pas',
  OcspStaplingTests in '..\src\OcspStaplingTests.pas',
  CertificateCheckTests in '..\src\CertificateCheckTests.pas',
  AsyncVerdictTests in '..\src\AsyncVerdictTests.pas',
  LiveRevocationTests in '..\src\LiveRevocationTests.pas',
  ConfigBuilderTests in '..\src\ConfigBuilderTests.pas',
  TrustCompositionTests in '..\src\TrustCompositionTests.pas',
  SystemTrustTests in '..\src\SystemTrustTests.pas',
  AppleAlertMapTests in '..\src\AppleAlertMapTests.pas',
  RootGenKeyingTests in '..\src\RootGenKeyingTests.pas',
  BundleTrustTests in '..\src\BundleTrustTests.pas',
  PresetTests in '..\src\PresetTests.pas',
  ExtensionCodecTests in '..\src\ExtensionCodecTests.pas',
  NegotiationTests in '..\src\NegotiationTests.pas';

{$R *.res}

begin
  Application.Initialize;
  if IsConsole then
    TextTestRunner.RunRegisteredTests
  else
    GUITestRunner.RunRegisteredTests;
end.
